### ISSUE TITLE
Add a multi-checkbox control setting field

### ISSUE THREAD

**Issue by mauryaratan** [analogwp/analogwp-templates#308]
We've "Remove Data on Uninstall" option at Settings. We need this option to support multiple-checkboxes beneath it to be displayed only if the Remove data option is checked.

*Note: Functionality is not to be written yet, just the settings.*

Here are the suggested settings:

- Remove Kits
- Remove all media files imported along Templates and Blocks
- Plugin Settings (checked by default)

**Comment by lushkant** [comment]
Make the default multiselect control appear with checkboxes.

**Comment by mauryaratan** [comment]
@lushkant should this be closed?

**Comment by mauryaratan** [comment]
@lushkant there's possibly a flaw with this.

Can you please confirm if each checkbox added, we can assign a different value? For example, on for one, off for next.

**Comment by lushkant** [comment]
All the above issues are addressed.

**Comment by lushkant** [comment]
All the issues listed above are addressed.

**Comment by lushkant** [comment]
I believe this is already well implemented, with our single checkbox.
Closing this one!
