### ISSUE TITLE
Test plugin UI with WordPress 5.4 beta

### ISSUE THREAD

**Issue by mauryaratan** [analogwp/analogwp-templates#335]
It appears that some buttons now have different hover styles because of changes in WordPress styles in v5.4. Lets test plugin UI thoroughly in both settings page and Editor page.

**Comment by lushkant** [comment]
`.is-tertiary` button class now has a hover behavior as well earlier it only was set to active states.
> This is just to account the changes, nothing that is abnormal.

Here's a screenshot referencing the same -
![Screenshot_2020-02-20 Style Kits Library ‹ latestwp — WordPress](https://user-images.githubusercontent.com/18240138/74913060-e9011580-53e5-11ea-8729-f1e2b46fa82a.png)

**Comment by mauryaratan** [comment]
@lushkant Please take care of this up next.

We need to check:

- Each UI instance in import flow of Templates, block, Style Kit. 
- Preview Windows
- Settings Page styles
- Theme Style Kit page
- Analog modal in Elementor editor

**Comment by lushkant** [comment]
All tested and good except the button changes mentioned above at Template import flow.
