### ISSUE TITLE
Default Template import method option in Settings

### ISSUE THREAD

**Issue by JohnPixle** [analogwp/analogwp-templates#380]
Under settings, I propose to add the following checkbox:

![Screenshot 2020-04-22 at 21 38 56](https://user-images.githubusercontent.com/4193672/80020584-f455e780-84e1-11ea-89a4-d8c51d6c4b6a.png)

What this does, is that instead of the user having to choose every time the SK to apply on the imported template, it always imports it with the global SK. So essentially, we get rid of this popup (both in the editor and the dashboard context):

![Screenshot 2020-04-22 at 21 41 54](https://user-images.githubusercontent.com/4193672/80021328-01bfa180-84e3-11ea-93a8-d135a4ea0515.png)

There are many advantages with this, and ideally reduces a lot of friction / confusion when importing the templates.

**Comment by gvgvgvijayan** [comment]
Demo video:
https://analogwp.slack.com/archives/CJ72D4S03/p1599646790000200

**Comment by JohnPixle** [comment]
Let's change the wording a bit:

![Screenshot 2020-10-19 at 11 08 41](https://user-images.githubusercontent.com/4193672/96418614-b79e4b00-11fb-11eb-9843-3151facf75f5.png)

As mentioned in Slack, in the editor popup we need to have an import button for importing directly into the page.


Also, the url for the "read more" will be: https://docs.analogwp.com/article/637-template-import-method
