### ISSUE TITLE
Redesign Templates Library

### ISSUE THREAD

**Issue by mauryaratan** [analogwp/analogwp-templates#384]
Blocks UI need to be redesigned on an independent page, for now.
It'll live basically along with other Elementor trigger buttons, as of its own.

See [mockup](https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=1286%3A8968).

**Comment by JohnPixle** [comment]
This is still in progress, but you can see an interactive Figma design showcasing the progress here:

https://www.figma.com/proto/kOdprBRtF7VB8hzWASXRx9/SK-UI-2?node-id=5%3A1&viewport=-973%2C471%2C0.5&scaling=min-zoom

**Comment by gvgvgvijayan** [comment]
> This is still in progress, but you can see an interactive Figma design showcasing the progress here:
> 
> https://www.figma.com/proto/kOdprBRtF7VB8hzWASXRx9/SK-UI-2?node-id=5%3A1&viewport=-973%2C471%2C0.5&scaling=min-zoom

Started and working on this new layout

**Comment by gvgvgvijayan** [comment]
@JohnPixle kindly share your thoughts, I completed all changes and deployed it.

**Comment by gvgvgvijayan** [comment]
@JohnPixle kindly share your thoughts. Completed spacing adjustments for the grids.

**Comment by JohnPixle** [comment]
Just to post here too, that the UI is fine so far. Apart from a minor positioning tweak that VJ is going through now, we can include it in the next release.

**Comment by gvgvgvijayan** [comment]
### Test Case:

1. For new change position of the dropdown control in the second row to the right of the first row in the template list, makes sure this affects only when the user clicks the "view templates" button of the template group instead of all template list which is visible when "Group by Template kit" switch is off.

**Comment by gvgvgvijayan** [comment]
@JohnPixle did the changes of controls in a single row instead of two rows in template and block group list.
