### ISSUE TITLE
Elementor migration from version 2.9 to 3

### ISSUE THREAD

**Issue by gvgvgvijayan** [analogwp/analogwp-templates#392]
# Removed wrapper which we are using:
elementor-row: [class-typography.php Line:439](https://github.com/analogwp/analogwp-templates/blob/develop/inc/elementor/class-typography.php#L439)
	
# Class prefix truncated:
Elementor truncated CSS class prefix from `.elementor-` to `.e-` applicable for the **newer** widgets, controls, or system elements but **not pre-existing** one. If you are developing extensions that manipulate existing system elements, controls or widgets, and used the `.elementor-` prefix before – we recommend you to follow this guideline and start using `.e-` instead in your new developments.

# Browser support:
No IE support.

**Comment by gvgvgvijayan** [comment]
Checked the following test cases:

1. Check loading of style kit library - Templates, Style Kits, Blocks tab
2. Check filters in Templates tab
3. Check filters in Blocks tab
4. check collections card in Templates tab
5. check collections card in Blocks tab
6. check "BACK TO KITS" in template list of a template collection
7. Check "BACK TO ALL BLOCKS" in block list of a block collection
8. Click "Preview" action in template card and check preview iframe DOM loaded
9. Click "Preview" action in style kits card and check preview iframe DOM loaded
10. Check "Go Pro" redirection in Templates, Style Kits and Blocks
11. Check import templates to library through import button in template card
12. Check import templates to page through import button in template card
13. Check import style kit to "Theme Style Kits" submenu page through import button in style kit card
14. Check import existing style kit to "Theme Style Kits" submenu page through import button and added new name in popup input of style kit card
15. Check import blocks through clicking import button in block card
16. Check in pages table (wp-admin/edit.php?post_type=page) able to apply global style kit for a page
17. Check able to edit with elementor for the page generated through analog template import
18. Check "Edit Theme Style Kit" by modify page properties in elementor kit panel controls
19. Check able to import widget into the elementor page and modify it's properties in control panel

**Comment by gvgvgvijayan** [comment]
Verified the elementor master branch still it hasn't removed class `elementor-row` for details please check the attached screenshot.
![elementor_v3_elementor-row](https://user-images.githubusercontent.com/4319097/86918161-e52b2100-c143-11ea-87fd-9bf450d96f92.png)

**Comment by mauryaratan** [comment]
@gvgvgvijayan Can you please double-check this on the beta they attached? It's possible that the branch we used wouldn't have that part of code merged?

**Comment by gvgvgvijayan** [comment]
# Issues

### Issue 1:

Visual Diff:
![sk_controls_missing](https://user-images.githubusercontent.com/4319097/87137998-60fba980-c2bb-11ea-99f3-ae85c5ad1ebb.png)

**Comment by gvgvgvijayan** [comment]
All test cases passed in
WP: 5.4.2
Elementor V3 Beta

**Comment by mauryaratan** [comment]
@lushkant is there anything in this issue that still needs to be done? If yes, let's create a separate issue with the task list and close this.

**Comment by gvgvgvijayan** [comment]
@mauryaratan ok I will close this. Future issues will be in its own ticket.
