### ISSUE TITLE
Unable to override accent color at linked icon widget by inline styles

### ISSUE THREAD

**Issue by lushkant** [analogwp/analogwp-templates#402]
Here's a replicated page at play site - https://play.analogwp.com/linked-icon-widget-issue/

Accent color takes precedence over the widget's inline color values.

![Screen Shot 2020-07-22 at 12 18 29 PM](https://user-images.githubusercontent.com/18240138/89024613-034f0000-d343-11ea-9b8e-c98f66a0293b.png)

**Comment by gvgvgvijayan** [comment]
After analyzed found that the issue can be resolved by adding a custom attribute `role="link"` in anchor tag's content panel. Please see the image for reference
![issue_402_anchor](https://user-images.githubusercontent.com/4319097/89868798-0793dc80-dbd1-11ea-9fd6-71e7577662aa.png)

CSS which responsible for this is: https://github.com/analogwp/analogwp-templates/blob/face01eb3e4506c65f03c61ebca8d0ae213caec0/inc/elementor/class-colors.php#L182

**Comment by mauryaratan** [comment]
@gvgvgvijayan That's not ideal solution. We need to tweak the actual CSS selector without requiring extra steps at users' end.

**Comment by gvgvgvijayan** [comment]
> @gvgvgvijayan That's not ideal solution. We need to tweak the actual CSS selector without requiring extra steps at users' end.

Alright, I understood.
