### ISSUE TITLE
Update the import popups

### ISSUE THREAD

**Issue by JohnPixle** [analogwp/analogwp-templates#416]
Currently when the user is trigerring the import popup inside the editor there is no way for him to actually import the template in the current page. I have updated the Figma designs, let's work on them as soon as possible, this needs to get out in the next update.

### Template Library Popup
[Figma link is here](https://www.figma.com/file/kOdprBRtF7VB8hzWASXRx9/SK-UI-2?node-id=488%3A693).

![template library popup](https://user-images.githubusercontent.com/4193672/92715537-4353ca80-f366-11ea-94f3-c94a643aa561.png)

### Editor Popup
 [Figma Link is here](https://www.figma.com/file/kOdprBRtF7VB8hzWASXRx9/SK-UI-2?node-id=488%3A507)

In this case we are adding a section to allow the user to import in the current page that he is working on.

![Editor popup](https://user-images.githubusercontent.com/4193672/92715688-7e55fe00-f366-11ea-9b1f-ee3a46c24ebf.png)

⚠️  The "How it Works" link should link to this url: https://docs.analogwp.com/article/545-importing-templates

**Comment by mauryaratan** [comment]
This looks good @JohnPixle, may I ask why the first section dropdown is still kept on left? Would be good to align that right as well to follow the pattern with rest of the fields.

**Comment by JohnPixle** [comment]
@mauryaratan good catch man.[ I updated the layout. ](https://www.figma.com/file/kOdprBRtF7VB8hzWASXRx9/SK-UI-2?node-id=488%3A506)
@gvgvgvijayan can you please make this quick adaptation?

![Screenshot 2020-09-15 at 10 42 12](https://user-images.githubusercontent.com/4193672/93180654-2b05f600-f740-11ea-8a37-c98584349161.png)

**Comment by JohnPixle** [comment]
These are all good to go @gvgvgvijayan great work on both UI and fixing the bugs.
