### ISSUE TITLE
When importing templates, the selected SK is not applied.

### ISSUE THREAD

**Issue by JohnPixle** [analogwp/analogwp-templates#417]
I only tested it when importing templates from the SK Template library, but looks like the global SK is applied regardless the user selection. On top of that, looks like the Theme Style Kit is not imported at all. Maybe this is the underlying issue.

https://www.loom.com/share/5b1020fa8b674706b1e4232959506853

**Comment by JohnPixle** [comment]
I think this works now as well, you may close this as well.

**Comment by gvgvgvijayan** [comment]
Noted
