### ISSUE TITLE
Manage SK panels is not effective at all

### ISSUE THREAD

**Issue by JohnPixle** [analogwp/analogwp-templates#418]
When toggling on and off the panels, the action does not have any effect on the editor. Panels are always visible. Maybe this is a result of the re-possitioning of the panels after the last elementor update? Assigning to @lushkant since you were the one who coded it?

![Screenshot 2020-09-10 at 13 28 18](https://user-images.githubusercontent.com/4193672/92717812-8c594e00-f369-11ea-915b-bf07dd7eccd7.png)

**Comment by lushkant** [comment]
@JohnPixle Got it, I'll test & add a fix asap. 🚀

**Comment by JohnPixle** [comment]
@lushkant I just checked at play and did not find this working. Perhaps you should push the update when you can?

**Comment by JohnPixle** [comment]
@lushkant I just tested and it works. let's wrap it up as well for the update
