### ISSUE TITLE
Where are the Default font sizes adjusted?

### ISSUE THREAD

**Issue by Ostii** [analogwp/analogwp-templates#444]
I've read the documentation [here](https://docs.analogwp.com/article/575-text-and-heading-sizes) and can't work out where to adjust the Default font size for Heading Sizes and Text Sizes.

![Style_Kits](https://user-images.githubusercontent.com/5764507/96946252-91461b80-152b-11eb-9382-e8a4fce40158.jpg)

**Comment by gvgvgvijayan** [comment]
The default size is the size controlled throw Elementor settings control. You can find that at `Site Settings` -> `THEME STYLE` -> `Typography` -> `H1 - H6 ` -> `Typography` -> edit icon -> `Size`.
