### ISSUE TITLE
It would be good to be able to update  font sizes within other modules

### ISSUE THREAD

**Issue by Ostii** [analogwp/analogwp-templates#445]
It would be good to be able to update  font sizes within other modules (Testimonial, Pricing etc.) to Small, Medium, Large etc.

![Style_Kits](https://user-images.githubusercontent.com/5764507/96946571-7627db80-152c-11eb-877e-c3f852a972fb.jpg)

**Comment by gvgvgvijayan** [comment]
The core idea of the style kits is centralized control to do all styling works, moreover, this is only possible if we know the exact placement of the custom section generated by custom plugins which practically non-achievable as there many numbers of plugins and every plugin based on its functionality and preference it may be placed anywhere in the panel like at layout panel or style panel or advanced panel or even at the global control panel. But our plugin main focus is centralized styling control so all in one global menu "Style Kits" under site settings.

**Comment by Ostii** [comment]
@gvgvgvijayan I think I understand what Style Kits is trying to do. I've been trying to do it myself via a CSS system for a few years now.

What I'm suggesting is not being able to change the size on all the modules offered by other plugin devs, but adding the 
same font size control that you use in the Heading module (see screenshot below) in the core Elementor pricing table for example.

From what I can see, I can currently only adjust that size manually, selecting an actual font size in each pricing table module. What I'm suggesting is that I'd choose from Sml, Med, Large, XL and XXL, but only in the Elementor and Elementor Pro modules.

![Elementor___Home](https://user-images.githubusercontent.com/5764507/97063253-4c34ee80-15ea-11eb-990e-9a806c3c8698.jpg)

**Comment by Ostii** [comment]
Hey @gvgvgvijayan I didn't hear anything back here. I thought I'd follow up on your comment above about there being many numbers of plugins....
I'm only talking about one plugin! The one that Style Kits is built to integrate with. Elementor.
And being able to choose the font sizes etc. within all the Elementor modules, not just the Headings module.

**Comment by gvgvgvijayan** [comment]
Hello @Ostii,

Sorry for the inconvenience. Our team will help you in this.

Cc @JohnPixle @mauryaratan

**Comment by JohnPixle** [comment]
This is a good idea, worth exploring it after some time.  Let's look into it after this update.

**Comment by JohnPixle** [comment]
I am leaving this as a note here.

We can definitely roll this out to some of "key" elements, and include "size" controls for the elements:

- Paragraph
- Icon Box
- Image box- Testimonial
- Animated Headline
- Posts 
- Archive posts

We can look into this into an upcoming release.

**Comment by lushkant** [comment]
With the inclusion of new Global fonts, this is no longer a requirement and Global fonts should be an efficient way to handle typography throughout the page.
