### ISSUE TITLE
How do I adjust inner section padding globally within Style Kits?

### ISSUE THREAD

**Issue by Ostii** [analogwp/analogwp-templates#446]
How do I adjust inner section padding globally within Style Kits?
This is as important as being able to adjust outer section padding.

![Style_Kits](https://user-images.githubusercontent.com/5764507/96946723-e8002500-152c-11eb-8c9e-4e53044d1b77.jpg)

**Comment by gvgvgvijayan** [comment]
You can achieve this using the `Column Gaps` control (present just beneath the `Outer Section Padding`. Using the combination of `Outer Section Padding` and `Column Gaps` you can control the various kind of spacing for the widget sections.

**Comment by Ostii** [comment]
@gvgvgvijayan From what I can tell so far, these controls you mention above control the padding at the top and bottom of a section, and the gap between columns, but not the gap at the top and bottom of a row (within a column).

What I'm suggesting is that there would be a Widget Space control that worked in the same way that the Column Gaps and Outer Section padding work in the Edit Section > Layout controls. There would be a choice of:

- Default
- No Padding
- Normal
- Small
- Medium
- Large
- Extra Large

This would make it much easier to maintain this spacing globally.

![Elementor___Home](https://user-images.githubusercontent.com/5764507/97063352-f4e34e00-15ea-11eb-88bb-230435fd3a0c.jpg)

![Elementor___Home](https://user-images.githubusercontent.com/5764507/97063434-733ff000-15eb-11eb-921c-e28e5c1681c8.jpg)
