### ISSUE TITLE
How to change colors of a heading

### ISSUE THREAD

**Issue by Ostii** [analogwp/analogwp-templates#448]
Why don't these match the Kali styles?

Where do I go when I want to change the colours of a heading? I can easily change the size on the Content tab but can't update the color from the Styles color palette. 

I have subsequently updated the colors to match the Kali Style Kit colors. Is this the best way to manage this?

![Style_Kits](https://user-images.githubusercontent.com/5764507/96947108-f4d14880-152d-11eb-81ff-66e5173ddd88.jpg)

**Comment by gvgvgvijayan** [comment]
These are global colors it means for a site you can use more than one style kits each have different color schemes which may not be possible show in this global control as there will be a conflict to show the colors. For e.e. if the site has three style kits like Kali, Volt, Architect each have their own set of color schemes and it's not possible to show in individual widget control.

Here you have chosen a heading widget if the style kit applies black color for all heading but you want to change the color for few headings means you can override the Style Kits styling by directly editing the specific widget to change the text color.
