### ISSUE TITLE
Check, is Style Kits able to translate using the plugin Loco Translate

### ISSUE THREAD

**Issue by gvgvgvijayan** [analogwp/analogwp-templates#453]
In Help Scout ticket: 5378 one of our customers said that Style Kits is not translatable using the plugin [Loco Translate](https://wordpress.org/plugins/loco-translate/)

Refer: #330

**Comment by lushkant** [comment]
Tested this PR, works just fine! 👍

**Comment by JohnPixle** [comment]
Shall I also close this one guys?

**Comment by lushkant** [comment]
Ram -
> when i generated zip, there’s a ang-translations.php file auto generated, which includes a syntax errors, basically a stray comma in 4-5th line
>  10up’s github action can take ZIP now, so technically we can build the whole thing including react app
