### ISSUE TITLE
💡 Add Default Spacer Gap

### ISSUE THREAD

**Issue by JohnPixle** [analogwp/analogwp-templates#53]
I dont know where to put it and is not urgent.. But it would be great to have a custom default value at the spacer element./

**Comment by JohnPixle** [comment]
This turns out to be important too

**Comment by mauryaratan** [comment]
Lets gear up on this @JohnPixle, can you provide me the values that you think should go with it?

**Comment by JohnPixle** [comment]
Yes @mauryaratan keep in mind that: 
Elementor allows you to define a global value under the elementor settings (default widget space) and in each column individually.

We need a responsive global control for this, default should be 20px for all viewports from now (as elementors default )

**Comment by medvedbne** [comment]
Would be good to have pre-defined for spacer perhaps? same as for headings?
Small, Large, XL, XXL ?

**Comment by zanga7** [comment]
I sometimes make a spacer element "global" then use it throughout my site.
